### ISSUE TITLE
Provide method to calculate latitude and longitude from adress

### ISSUE THREAD

**Issue by felix-kaestner** [ordered-online/locations#1]
https://github.com/ordered-online/locations/blob/5c68f15642559d29a4000b53907be6b5a74ec121/locations/locations/views.py#L211

Please provide a method to calculate latitude and longitude from adress. In my opition this should not be handled by the client.

**Comment by PhilippMatthes** [comment]
This is a non trivial task, because it requires geocoding. Thankfully, Google already provides a Geocoding API. This feature will not be encapsulated by the locations service. Please request the longitude/latitude in the client. Note: on iOS, there is already a possibility to geocode based on the given SDK, so on iOS we won‘t need Googles Geocoding API, but I think it‘s the only feasible option for Android.

**Comment by FKasy** [comment]
What prevents us from using auch an API in the locations service ? Like you said, implementations of such API may differ depending on the Platform. Since the client is a hybrid app (meaning web, ios and android) this could lead to code which has be implemented multiple times for the different platforms. So to avoid this issue the typicall solution would be to use an online endpoint for geocoding. In terms of  application flow,  that would be cumbersome since  a request has to send from the client  to some online  endpoint before being forwarded  further to the locations  servive ( notice 2 post request to different services). Additionally including further API in the client  application would further  inflate the already heave  dependency tree of the client. Furthermore there would be no validation! What prevents malware  or failure  on the client from creating a false mapping between address and geolocation ? By shifting this task to the backend we avoid this problem aswell. Also, by using a geocode  API (packages  are probably already available for   python / django, no need to implement ourself) we could  use the same for finding the location  nearby. The last point I like to make is  that this feature we are talking about is application logic. The client should stay what it is ment to be, which is a front end to our application logic handled by micro services in the back end. Things like translating adress information to geolocation should be handled by the locations service, IMHO.

**Comment by FKasy** [comment]
Also notice that the geolocation of the  restaurant/bar/etc. is not related to the geolocation  of the client! Owners do  not need be at the location in order to create it. In fact, things  like geolocation of the client is  a feature natively included in react native. There is no need for platform dependent  code or APIs. This feature is  indeed already used. But  rather in the situation of a customer finding a restaurant that is nearby his current location.

**Comment by PhilippMatthes** [comment]
How would your proposed solution look like? Provide an endpoint which wraps Google Geocoding API and provides it via GET mapping?

**Comment by PhilippMatthes** [comment]
In the first prototype, will there be text input based location search? I thought we‘d stick to the scan-a-qr-code model at first and maybe look into text search when we have time. So my question is, is this needed during your current prototype development? If yes, I can assign this to me and get it done by 1-2 days. If no, we should mark this as revisit later.

**Comment by FKasy** [comment]
> How would your proposed solution look like? Provide an endpoint which wraps Google Geocoding API and provides it via GET mapping?

No. Actually my proposed solution would be to use the already great [GeoDjango](https://docs.djangoproject.com/en/2.2/ref/contrib/gis/) which is already included in Django ! The [AsGeoJson](https://docs.djangoproject.com/en/2.2/ref/contrib/gis/functions/#asgeojson) method provides a simple implementation which we could try to use. The Application flow should be as follows:
1. Location owner enters the address on the client application together with other meta data regarding the location (name, description, website, ....)
2. This data is sent via a post request to the already implemented endpoint '/locations/create/'.
3. The locations service translate the address to a GeoJson object (as mentioned above) which is then stored together with the other location data.
4. All data about the location (including the new GeoJson) ist returned to the client as the respone of the request.

**Comment by FKasy** [comment]
> In the first prototype, will there be text input based location search? I thought we‘d stick to the scan-a-qr-code model at first and maybe look into text search when we have time. So my question is, is this needed during your current prototype development? If yes, I can assign this to me and get it done by 1-2 days. If no, we should mark this as revisit later.

In the final application there should be both search through a text input via the '/locations/find/', aswell the possibility to search locations nearby. The later will actually first request permissions to GPS data on the client(Android, iOS, Web) and then fetch the closest location based on the '/locations/nearby/' endpoint. For the current prototype this is not a breaking feature ! I still have other tasks which I need work on. That is also why I tagged this Issue as '**enhancement**' rather than anything other.

**Comment by FKasy** [comment]
> > How would your proposed solution look like? Provide an endpoint which wraps Google Geocoding API and provides it via GET mapping?
> 
> No. Actually my proposed solution would be to use the already great [GeoDjango](https://docs.djangoproject.com/en/2.2/ref/contrib/gis/) which is already included in Django ! The [AsGeoJson](https://docs.djangoproject.com/en/2.2/ref/contrib/gis/functions/#asgeojson) method provides a simple implementation which we could try to use. The Application flow should be as follows:
> 
> 1. Location owner enters the address on the client application together with other meta data regarding the location (name, description, website, ....)
> 2. This data is sent via a post request to the already implemented endpoint '/locations/create/'.
> 3. The locations service translate the address to a GeoJson object (as mentioned above) which is then stored together with the other location data.
> 4. All data about the location (including the new GeoJson) ist returned to the client as the respone of the request.

If this approach is to complex, we can still use the [google maps API services for python](https://github.com/googlemaps/google-maps-services-python) which is actually easy to use and provides all our use cases.
