### ISSUE TITLE
Infer location owners by verification credentials

### ISSUE THREAD

**Issue by felix-kaestner** [ordered-online/locations#2]
https://github.com/ordered-online/locations/blob/5c68f15642559d29a4000b53907be6b5a74ec121/locations/locations/views.py#L266

We should enforce that a user can only create locations for him/herself. By not having a "user_id" field inside the "location" key of the "createLocation" endpoint we do not make it possible to create locations for other users. ( Why is this included ? )
The user / owner of the location should always be read from the associated user id of the request.

**Comment by PhilippMatthes** [comment]
> We should enforce that a user can only create locations for him/herself

We already do so, by checking:
1. that the passed user id and the session key are valid (i.e, that the user is authenticated)
2. that the user id for the location to be created is the same as verified beforehand by the verification service

> By not having a "user_id" field inside the "location" key of the "createLocation" endpoint we do not make it possible to create locations for other users. ( Why is this included ? )

First of all, the user id is passed twice, in the request body, one for the location (to conclude ownership) and one for the verification. And yes, it is not possible for a user to create a location for another user, which is correct behaviour.

> The user / owner of the location should always be read from the associated user id of the request

I don‘t understand this. Do you mean, we should remove the user_id field? This is not possible, because, as I said, we need to verify that the user is the location owner.

**Comment by FKasy** [comment]
The actual point is that I don't see any reason at all, why we need to include the user id twice in the same request ?! Since we enforce that it is the same that is totally unnecessary. The request should only  contain  the user id  once.

**Comment by FKasy** [comment]
What  prevents  you from  using the same user id ( you use for authentication ) to create the location afterwards?

**Comment by PhilippMatthes** [comment]
Ok then I misunderstood this issue. I will change the title accordingly.

**Comment by PhilippMatthes** [comment]
I initially thought you were pointing out the model field, and not the request parameter.

**Comment by felix-kaestner** [comment]
@PhilippMatthes should I resolve this issue ?

**Comment by PhilippMatthes** [comment]
If you want to, you can resolve this.

**Comment by felix-kaestner** [comment]
Fixed in e55f9c200dce1b98b8d90fe51d3b4fae46cc8449
